name = "rosa-rf"
author = "raspmary"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "852a06667579b8a6eee8412a3d08c8cc826005ccef60e167f82627e8bd96ccc6"

[versions]
forge = "43.5.1"
minecraft = "1.19.2"
